### ISSUE TITLE
cpe_remote - add feature if package version is higher than version expected

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#113]
I know this kind of goes against the whole "desired state", but this would help when testing new versions of tools without chef downgrading them immediately on the next run.

**Comment by erikng** [comment]
ping @mikedodge04

**Comment by mikedodge04** [comment]
We talked about this. I think you should set the version in the api for that pkg for that user. If you want to write the version checking logic go head. But with mac pkg versions the way there are I believe this will be non trivial and not worth the effort.

**Comment by erikng** [comment]
That's fine. I found an appropriate workaround actually by just uploading a new version and using that with a conditional statement.
