### ISSUE TITLE
initialization error in adobe_api.py (adobe_tools branch)

### ISSUE THREAD

**Issue by adobeDan** [facebook/IT-CPE#116]
Commit 5822bc94 in the adobe_tools branch introduced an error at lines 56-64 of [adobe_api.py](https://github.com/facebook/IT-CPE/blob/5822bc94e8056ab6feb3dac657959c5a8b20f8d3/adobe_tools/adobe_api.py).  A copy of the `__init__` function header, which was supposed to be indented along with the other members of the class, was left exdented and so the other members weren't defined.

**Comment by nmcspadden** [comment]
This was fixed by ca86af6.
