### ISSUE TITLE
failure to cache productlist in the adobe_tools branch

### ISSUE THREAD

**Issue by adobeDan** [facebook/IT-CPE#117]
as of commit 5822bc94, the `__init__` of `AdobeAPIObject` was failing to gather and cache the `productlist` member of the cached data, and so the product list is always fetched from the server.

See lines 170-172 of [adobe_api.py](https://github.com/facebook/IT-CPE/blob/5822bc94e8056ab6feb3dac657959c5a8b20f8d3/adobe_tools/adobe_api.py) for details.  I would suggest calling `gather_product_list` at that point in the initialization.

**Comment by nmcspadden** [comment]
Fixed in a171b85b8adf4c08bd05a4227fb8e13078a7d300.
