### ISSUE TITLE
Request increase in splay period for AdobeAPIObject data caching

### ISSUE THREAD

**Issue by adobeDan** [facebook/IT-CPE#118]
Given the number of machines using the Adobe UM API, having a +/- splay of 3 days (72 hours) in the cache life is probably insufficient to get below the Adobe throttling limits.  I suggest updating the default splay to be +/- 6 days (144 hours).  This will spread things evenly of the course of the default two week cache period.

**Comment by nmcspadden** [comment]
Fixed in e11cea78bc0391a1135fe5fa9951f88051a60d16.
