### ISSUE TITLE
cpe_chrome doesn't work until Spotlight is finished indexing

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#129]
As discussed, I discovered cpe_chrome was failing during our DEP enrollments due to Spotlight not finishing indexing during the initial bootstrap.

Chrome is integral in our deployment (and is installed on all machines), so for now I have opted to disable the `return unless node.installed?('com.google.Chrome')` function. The Master Preference functionality is a one-time thing, so it is crucial that it works.

Perhaps a case should be written to look for Google Chrome in it's default installation path(s) and if we don't find it there, then use the cpe_utils spotlight functionality.

**Comment by mikedodge04** [comment]
https://github.com/facebook/IT-CPE/pull/134

**Comment by mikedodge04** [comment]
Fixed with attached PRs
