### ISSUE TITLE
Chocolatey Packages

### ISSUE THREAD

**Issue by discentem** [facebook/IT-CPE#147]
Hi CPE, 
I'd be very interested to see Chocolatey packages Facebook has written be open-sourced, similar to the Autopkg Recipes that have been open-sourced over at https://github.com/facebook/Recipes-for-AutoPkg. This would be a great help to me and I think the community as well!

Thanks, 
Brandon

**Comment by gbatye** [comment]
Hello, 

We don't do anything special with chocolatey packages to justify opensourcing.  A majority of our internal packages are modified versions from chocolatey.org to fit our organizations needs. On top of that, we haven't taken advantage of the automatic package framework which you might be alluding to.   

FWIW, here is general template we follow when creating new packages. 

```
$splat = @{
  'PackageName' = 'example;
  'FileType' = 'msi;
  'SilentArgs' = 'AGREETOLICENSE=Yes /quiet';
  'Url' = 'https://example.com/package.msi;
  'Checksum' = 'checksum';
  'ValidExitCodes' = @(0, 1603);
}

Install-ChocolateyPackage @splat
```

**Comment by discentem** [comment]
Thanks for the example @gbatye.
