### ISSUE TITLE
please open source cpe_chefctl/cpe_chef_client

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#150]
This comes up time and time again, even internally about how to properly manage chef runs, post initial deployment.

Many people end up using small launchdaemons controlled by things like `cpe_launchd`, but given that Facebook already open sources chefctl, it would be awesome if the (giant) CPE team could open source their controls over this.

@clburlison has somewhat addressed this situation, but I would love to see a battle-tested at scale, multiple OS version of this.

**Comment by erikng** [comment]
https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_init/recipes/default.rb#L15-L16

**Comment by johnnyramos** [comment]
more or less this - https://github.com/facebook/chef-utils/tree/master/chefctl

**Comment by erikng** [comment]
Right, but I want the wrapper around this. There's tons of gotchas and things to look out for that I'd rather not deal with/write, when someone has already done it.

**Comment by natewalck** [comment]
I cut a task to look at what we have internally and possibly open source
it.

**Comment by erikng** [comment]
We can close this since Uber now open sourced our version of cpe_chefctl, cpe_chefclient and cpe_chef_handlers.
