### ISSUE TITLE
cpe_remote - uninitialized constant CPE::Distro

### ISSUE THREAD

**Issue by johnnyramos** [facebook/IT-CPE#160]
Seems `CPE::Distro` is referenced throughout `cpe_remote` cookbook. I don't see it initialized anywhere within the repo so I'm not sure if this is public.

https://github.com/facebook/IT-CPE/blob/9f3bbb25d7ffd920ba47b96d5d04ce1e5e670ea8/chef/cookbooks/cpe_remote/libraries/helpers.rb#L14

https://github.com/facebook/IT-CPE/blob/9f3bbb25d7ffd920ba47b96d5d04ce1e5e670ea8/chef/cookbooks/cpe_remote/resources/file.rb#L71

Chef run would get:
```
        ================================================================================
        Error executing action `create` on resource 'cpe_remote_file[fupayme.pkg]'
        ================================================================================

        NameError
        ---------
        uninitialized constant CPE::Distro

        Cookbook Trace:
        ---------------
        /var/chef/cache/cookbooks/cpe_remote/resources/file.rb:71:in `block (2 levels) in class_from_file'
        /var/chef/cache/cookbooks/cpe_remote/resources/file.rb:65:in `block in class_from_file'
```

This is on Chef 14 if that matters.

**Comment by johnnyramos** [comment]
Tested on `13.8.5` as well:
```
        ================================================================================
        Error executing action `create` on resource 'cpe_remote_file[urexgf.pkg]'
        ================================================================================

        NameError
        ---------
        uninitialized constant CPE::Distro

        Cookbook Trace:
        ---------------
        /var/chef/cache/cookbooks/cpe_remote/resources/file.rb:71:in `block (2 levels) in class_from_file'
        /var/chef/cache/cookbooks/cpe_remote/resources/file.rb:65:in `block in class_from_file'
```

**Comment by gbatye** [comment]
@johnnyramos 

What's up???

I have a diff up internally to test a change that will fix this issue. Hopefully will be it pushed within a few days.  If you can't wait, you can add a auth_headers method to cpe_remote/libraries/
helpers.rb and replace all call sites of `CPE::Distro.auth_headers` with `auth_headers`

this is the auth_headers method I'm testing
```
def auth_headers(url, method)
      CPE::Distro.auth_headers(url, method)
    rescue StandardError
      Chef::Log.warn('Building auth headers failed')
      {}
    end
```
