### ISSUE TITLE
cpe_chrome references node.person which doesn't exist in cpe_utils

### ISSUE THREAD

**Issue by johnnyramos** [facebook/IT-CPE#172]
For Windows, the `cpe_chrome` cookbook references `node.person` in which I'm assuming you're using from an internal `cpe_utils` 😉 - `node_functions.rb`. Unless I'm missing something else here? 🙈 

Places called:
https://github.com/facebook/IT-CPE/blob/66a71bb40de1623a99a6787225e409b92694ff27/chef/cookbooks/cpe_chrome/resources/cpe_chrome_win.rb#L35

https://github.com/facebook/IT-CPE/blob/66a71bb40de1623a99a6787225e409b92694ff27/chef/cookbooks/cpe_chrome/resources/cpe_chrome_cleanup.rb#L29

Also, we don't need to know your business since we can't use intern as well 😢 :
https://github.com/facebook/IT-CPE/blob/66a71bb40de1623a99a6787225e409b92694ff27/chef/cookbooks/cpe_chrome/resources/cpe_chrome_win.rb#L31-L34

https://github.com/facebook/IT-CPE/blob/66a71bb40de1623a99a6787225e409b92694ff27/chef/cookbooks/cpe_chrome/resources/cpe_chrome_win.rb#L47-L50

https://github.com/facebook/IT-CPE/blob/66a71bb40de1623a99a6787225e409b92694ff27/chef/cookbooks/cpe_chrome/resources/cpe_chrome_win.rb#L60-L63

**Comment by nmcspadden** [comment]
Fixed by #175
