### ISSUE TITLE
cpe_remote auth headers

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#177]
the cpe_remote cookbook currently warns if auth headers are not passed, but there is no actual way for people using the cookbook to pass these as it's an internal feature to FB. Could this be generalized and added to the cookbook?

I would love to have auth header usage to protect the chef_remote repo urls

**Comment by clburlison** [comment]
For what it's worth this can be accomplished right now by editing `cpe_remote/libraries/helpers.rb` file with the following:

```ruby
    def auth_headers(url, method)
      #CPE::Distro.auth_headers(url, method)
      require 'base64'
      {'AUTHORIZATION' => "Basic #{
        Base64.strict_encode64('username:password')}",
        'Content-Type' => 'application/data'
      }
    rescue StandardError
      Chef::Log.warn('Building auth headers failed')
      {}
    end
```

I tried a few variations of creating a `CPE::Distro.auth_headers` function in a separate helper library file but came up unsucessful. I'm sure that was user error on my part 🤷‍♂️ 

As for Erik's comment I think this could solved in the README as a new "authorzation" section. It would be nice to document how to add the CPE::Distro.auth_headers format so we could keep this in a sepreate non-cpe_remote cookbook.

Cheers

**Comment by DNSGeek** [comment]
Don't think this is still needed.

**Comment by natewalck** [comment]
Why is this no longer needed? Has cpe_remote been updated to have this functionality?

**Comment by erikng** [comment]
Definitely still needed if the support hasn't been added.
