### ISSUE TITLE
Swap cpe_launchd and cpe_profiles in runlist

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#187]
I have an interesting situation that I think others may eventually run into and I was thinking as a best practice, that we should flip cpe_launchd and cpe_profiles in the cpe_init runlist that you provide as an example:

https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_init/recipes/mac_os_x_init.rb#L46-L47

I have a cookbook I wrote that uses cpe_launchd to create a LaunchAgent, but this app kind of sucks and needs to have the preferences available _prior_ to the app launching.

With cpe_profiles after cpe_launchd in the run list, this makes it a bit hard.

I could write some new `has_profile?` in cpe_utils, but this seems like a better and easier approach.

**Comment by mikedodge04** [comment]
feel free to put up a pr to swap the order
