### ISSUE TITLE
cpe_remote claims some URLs are invalid

### ISSUE THREAD

**Issue by natewalck** [facebook/IT-CPE#192]
cpe_remote will say a url is invalid, yet the URL works as expected everywhere else (including curl/wget). In this specific case, it is a redirect to a shortlived AWS URL with creds/auth as parameters on the redirected URL.

Example URL: https://github.com/salopensource/sal-scripts/releases/download/2.1.3/sal_scripts.pkg

It should probably handle whatever redirects github does (as this is common elsewhere too).

**Comment by nmcspadden** [comment]
What's the proposed fix for this?

**Comment by nmcspadden** [comment]
I don't intend to spend any time fixing this, as this isn't something that causes us any immediate problems. If you've got a PR to fix it, we'll probably merge it.
