### ISSUE TITLE
cpe_remote should be able to force install expired packages

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#202]
much like munki, I think cpe_remote should be able to install a package should the package expire suddenly. Could be done like this: https://github.com/munki/munki/wiki/Allowing-Untrusted-Packages

Alternatively, let cpe_remote not hard fail and destroy chef runs.

**Comment by nmcspadden** [comment]
Agreed, this should be a configurable option. That seems relatively easy enough to implement.

**Comment by nmcspadden** [comment]
We have no immediate plans to work on this. I do agree it seems like a reasonable configurable option _in general_, but we would never allow it internally.

**Comment by nmcspadden** [comment]
After some thought, we have decided not to work on this. It's not something we plan to ever do internally, so we're not going to develop it.
