### ISSUE TITLE
Undefined method error when trying to define ManagedBookmarks via cpe_chrome on Windows

### ISSUE THREAD

**Issue by andrewjharms** [facebook/IT-CPE#224]
I'm getting the following error when trying to use `cpe_chrome` to set ManagedBookmarks on a Windows system:

`NoMethodError: undefined method 'encode' for ["name", "My Bookmark"]:Array`

Here's how I'm setting the node attribute:
```
node.default['cpe_chrome']['profile']['ManagedBookmarks'] = [
  {
    'name' => 'My Bookmark',
    'url' => 'https://google.com'
  },
  {
    'name' => 'Another Bookmark',
    'url' => 'https://google.com'
  }
]
```

**Comment by andrewjharms** [comment]
Looks like changing ManagedBookmarks from `:multi_string` to `:string` prevents the error.  However, bookmarks are not getting created properly. Here's some notes from me trying to debug why:

- The ManagedBookmarks key can accept a few different formats (see https://www.chromium.org/administrators/complex-policies-on-windows). I'm assuming the desired output would be a single JSON string value for the ManagedBookmarks key.
- When multiple bookmarks are defined, separately indexed keys are getting created - one for each bookmark - due to the `if data_has_mulitple_entries?` logic in `to_chef_reg_provider`. Assuming the desired output is a single JSON string, this logic should be modified to exclude ManagedBookmarks (as well as any other potential keys that require JSON strings for values).
- The `registry_key` resource call in `cpe_chrome_win.rb` uses the full path for the key, e.g. `HKLM\\Software\\Policies\\Google\\Chrome\\ManagedBookmarks`. This additional folder/subkey is not required and should be at the root (`HKLM\\Software\\Policies\\Google\\Chrome`). Changing the `registry_key` resource to use `setting.path` instead of `setting.fullpath` solves this but may break other keys. The reference registry file linked in the source should be reviewed again to match the hierarchy (https://dl.google.com/dl/edgedl/chrome/policy/policy_templates.zip)
- Unsurprisingly, using Ruby hash rockets syntax in the value of the ManagedBookmarks key results in an invalid JSON string, so bookmarks don't get created. The bookmarks do get created after changing the hash rockets to colons/proper JSON.

I will try to start a PR to address some of these things, but would appreciate some feedback on the above so I know that I'm taking the right approach.

**Comment by svmastersamurai** [comment]
Thanks for the bug report. I have a patch internally for this specific setting that should be up shortly.

**Comment by andrewjharms** [comment]
Thanks @svmastersamurai, let me know how I can help with a PR.

**Comment by andrewjharms** [comment]
Oh, I see you committed a patch yesterday: https://github.com/facebook/IT-CPE/commit/435f87c73888cc2f8bc9adabf910ce75cc65d79b

Thanks! Will test soon.

**Comment by andrewjharms** [comment]
Works great! Thanks for the patch.
