### ISSUE TITLE
cpe_nomad is still using fb_launchd

### ISSUE THREAD

**Issue by Julian-O-SF** [facebook/IT-CPE#238]
In [this diff](https://github.com/facebook/IT-CPE/commit/3671f415da24ac4611450690911a774e3a8ac541) you back out a change and shifted cpe_nomad to use cpe_launchd (away from fb_launchd), but in your `configure_launchd` you still use fb_launchd.

[Link to code](https://github.com/facebook/IT-CPE/blob/master/itchef/cookbooks/cpe_nomad/resources/darwin.rb#L152-L170)

Paste of lines 152-170
```
  def configure_launchd
    launchd lddomain do
      only_if do
        ::File.exist?("/Library/LaunchAgents/#{lddomain}.plist")
      end
      type 'agent'
      action :nothing
    end
    node.default['fb_launchd']['jobs'][lddomain.split('.')[-1]] =.    < --- This line
      node.default['cpe_nomad']['launchagent']
  end

  def profile_domain
    "#{node['cpe_profiles']['prefix']}.nomad"
  end

  def lddomain
    "#{node['fb_launchd']['prefix']}.nomad"                 < --- This line
  end
```

I'm happy to do a quick PR to pull it back, but you may want to take a closer look at the sync tool to see where else this didn't get backed out correctly.

**Comment by svmastersamurai** [comment]
Nothing wrong with the sync here, this must have slipped through the cracks. We're happy to accept a PR for this.

**Comment by Julian-O-SF** [comment]
Thanks, PR submitted!

**Comment by nmcspadden** [comment]
I'm sorry, this is my fault for not checking. This is intentional. Eventually, we're going to change all of them over. I changed this manually as a 'first pass' - the one we reverted was broken, but these are effective, and this will be the correct way forward in the future.
