### ISSUE TITLE
Create a migration path from the old chef code to the new chef code

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#244]
### Describe the Enhancement:
I would like to see a `cpe_utils` cookbook come back, that simply calls `cpe_helpers`. Since `cpe_helpers` contains all the similar `node` calls, this should not result in any regressions and allow other providers to slowly move their cookbooks one at a time to `cpe_helpers`.

If `cpe_utils` is being used, it should give a warning on every chef run to encourage people off of it, otherwise it will have to be maintained from here on out.

Once all CPE repositories have moved to `cpe_helpers`, we can kill this transition cookbook.

### Describe the Need:
When trying to slowly move from `cpe_utils` to `cpe_helpers`, it gets a bit stressful. With `cpe_utils` gone from this repo, it is somewhat unclear how other companies/repositories can successfully migrate, without multiple cookbook changes being done all at once.

This ultimately is a metadata issue as you cannot conditionally set them up with the CPE/API driven model (due to no-versioning).

### Current Alternative
Changing every cookbook you have in one single sweep and hoping nothing breaks.

### Can We Help You Implement This?:
I commit to helping with PR's across the various cookbook repositories in moving over to `cpe_helpers` if Facebook can help design an official migration path for the community. As it stands, the community is essentially in a forked state, which will be a barrier for new companies trying to get started with this model.

**Comment by dtheyer** [comment]
Closing this since this is stale and hopefully most users have already migrated by now.
