### ISSUE TITLE
Chef 16.2 breaking changes and consistency in cookbooks

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#246]
### When a Change Needs a Design Proposal
With Chef 16.2 now released, I am auditing all of the various cookbooks across repositories and seeing many inconsistencies that I believe we can and should correct.

Single platform cookbooks:
Method 1:
- cpe_applocker/recipes/default.rb
  - calls cpe_applocker resource
    - calls uninstall action
    - calls configure action
- cpe_adobe_flash/resources/cpe_applocker.rb
  - one action_class in the **middle** of the resource
  - two separate actions at the **bottom** of the resource
```
resource_name :cpe_applocker
provides :cpe_applocker, :os => 'windows'
default_action :configure
```

Method 2:
- cpe_dconf/recipes/default.rb
  - calls cpe_dconf resource
- cpe_dconf/resources/cpe_dconf.rb
  - one action block line including name at the **top** of the resource
```
resource_name :cpe_dconf
provides :cpe_dconf, :os => 'linux'
default_action :update
```

Method 3:
- cpe_deprecation_notifier/recipes/default.rb
  - calls cpe_deprecation_notifier resource
- cpe_adobe_flash/resources/cpe_applocker.rb
  - one action_class at the **bottom** of the resource
    - class is memoized
```
resource_name :cpe_deprecation_notifier
provides :cpe_deprecation_notifier, :os => 'darwin'
default_action :prompt
```

Multiplatform cookbooks:
Method 1:
- cpe_adobe_flash/recipes/default.rb
  - calls single cpe_adobe_flash resource
- cpe_adobe_flash/resources/ACTION_adobe_flash_OS_TYPE.rb
  - explicit resource name
  - un-explicit provides, explicit os support
  - one action block with multiple sub-actions at the **bottom** of the resource
```
resource_name :cpe_adobe_flash_darwin
default_action :config
provides :cpe_adobe_flash, :os => 'darwin'
```

Method 2:
- cpe_chrome/recipes/default.rb
  - calls single cpe_chrome resource
- cpe_chrome/resources/cpe_chrome_OS_TYPE.rb
  - explicit resource name
  - un-explicit provides, explicit os support
  - one action block with multiple sub-actions at the **top** of the resource
```
resource_name :cpe_adobe_flash_darwin
default_action :config
provides :cpe_adobe_flash, :os => 'darwin'
```

These are just some of the examples.

there are other method examples that would take me hours to document, but some cookbooks that do not follow any of these models:
- cpe_flatpack
- cpe_gnome_software (not chef 16 compliant)
- cpe_hosts
- cpe_kernel_channel
- cpe_launchd
- cpe_munki (not chef 16 compliant, but I think this is one of the best models for single OS, multiple resource)
- cpe_nomad/cpe_vfuse (resource file name darwin does not match the resource name it provides)
- cpe_pathsd (resources could be combined similarly to cpe_chrome)
- cpe_preferencepanes (resource file name default does not match the resource name it provides)
- cpe_remote (provides line is in a different place than other cookbooks)
- cpe_spotlight (not chef 16 compliant, recipe has strange guards that should likely be put in the resource itself)
- fb_launchd (fail in recipe)

Gusto, Pinterest and Uber's cookbooks have a few other examples of different methods.

## Specification
We should come up with some methods and adhere to them - perhaps even co-author linter rules that can enforce these.

I believe we can bring this down to the following:

Single Platform cookbook

1. single resource (`foo.rb` with a `configure` resource block)
2. multiple resources, classified by the responsibility (`configure.rb` `install.rb`).

Multi Platform cookbook

1. single resource per OS (`macos.rb`, `windows.rb`) or `unix.rb` if it can handle multiple things (like darwin and ubuntu)
2. multiple resources, classified by the responsibility (`configure.rb` `install.rb`).

Guards
Guards should either be in the resource or the recipe, but likely not both.

Multiplatform code deduplication
Libraries and/or attribute files should be designed for multi-platform so that code is not repeated across multiple resources. I think this will be the most pertinent/long part of the discussion and we may not be able to agree or come up with a solution for all cases.

**To be clear, this is merely a suggestion and I am very open to differing opinions.**

## Downstream Impact
This should offer no downstream impact other than making it for consistent and creating a model that others can follow when "taking inspiration" from other open source cookbooks.

**Comment by erikng** [comment]
One thing that isn't clear, but internally I have a diff to change all of the resources to:

```
resource_name :foo
provides :cpe_foo, :os => 'foo' OR ['foo', 'bar']

default_action :foo

EVERYTHING ELSE HERE
```

This allows all cookbooks to be chef 16.2 compatible

**Comment by erikng** [comment]
For context about how this started: https://github.com/chef/chef/blob/master/RELEASE_NOTES.md

## Breaking Change in Resources

In Chef Infra Client 16.0, we changed the way that custom resource names are applied in order to resolve some longstanding edge-cases. This change had several unintended side effects, so we're further changing how custom names are set in this release of Chef Infra Client.

Previously you could set a custom name for a resource via `resource_name` and under the hood this would also magically set the `provides` for the resource. Magic is great when it works, but is confusing when it doesn't. We've decided to remove some of this magic and instead rely on more explicit `provides` statements in resources. For cookbooks that support just Chef Infra Client 16 and later, you should change any `resource_name` calls to `provides` instead. If you need to support older releases of Chef Infra Client as well as 16+, you'll want to include both `resource_name` and `provides` for full compatibility.

**Pre-16 code:**

```ruby
resource_name :foo
```

**Chef Infra Client 16+ code**

```ruby
provides :foo
```

**Chef Infra Client < 16 backwards compatible code**

```ruby
resource_name :foo
provides :foo
```

**Comment by michel-slm** [comment]
https://github.com/facebook/IT-CPE/commit/0be482b88be4fc009ba14a62446c07f1366d654a and https://github.com/facebook/IT-CPE/commit/67221eb12604656f53b424a7558d7902b9b4ae74 address this -- but there were infra issues landing and pushing these so they might have been delayed in showing up here. Thanks for reporting!

**Comment by erikng** [comment]
hey @michel-slm this does not address the major point in this issue. This merely addresses the 16.2 breaking change.

I kindly ask that you re-open this issue.

**Comment by erikng** [comment]
There are at least 15 **different** styles that the cookbooks adhere to.

**Comment by michel-slm** [comment]
Yeah, sorry, being oncall and putting down fires, I missed the "consistency" part

**Comment by michel-slm** [comment]
For style - Facebook/chef-cookbooks guards in the recipe, and fail hard when imported on the wrong platform. This is probably makes the most sense combined with further declaring provides with the os/platforms that are supported - that way attempts to import on an unsupported platform gets the consistent message from the recipe.

CPE cookbooks traditionally don't fail, just skip, when imported on an unsupported platform, and a lot of the gating code is in the resources themselves. I agree this needs to be refactored - I've never been happy with it but in the past we've not been aligning our cookbooks with the other repo.

**Comment by dtheyer** [comment]
Closing this since it is stale and our cookbook style has changes significantly in the last two years.
