### ISSUE TITLE
cpe_remote ruby warning in Chef 16.2.73

### ISSUE THREAD

**Issue by erikng** [facebook/IT-CPE#251]
## Description
When running cpe_remote I noticed this warning today:

`* cpe_remote_pkg[foo] action installnil versions are discouraged and will be deprecated in Rubygems 4`

## Chef Version
Chef 16.2.73

## Platform Version
macOS 10.15.6

## Replication Case
Install a new package with `cpe_remote_pkg`

## Client Output
```
* cpe_remote_pkg[foo] action installnil versions are discouraged and will be deprecated in Rubygems 4
```

**Comment by aparnamaleth** [comment]
I'm unable to repro this warning. Feel free to reopen if you still get this warning.

**Comment by dtheyer** [comment]
Closing since I also do not see this warning and this issue has become stale
