### ISSUE TITLE
`rescue StandardError` in fb_helpers

### ISSUE THREAD

**Issue by ChefAustin** [facebook/IT-CPE#264]
There's a few instances of `rescue StandardError` in `fb_helpers/libraries/node_methods.rb`  (https://github.com/facebook/IT-CPE/blob/main/itchef/cookbooks/fb_helpers/libraries/node_methods.rb) and that should probably be re-evaluated.

**Comment by dtheyer** [comment]
Issues related to cookbooks prefixed with fb_ should be created on this repo: https://github.com/facebook/chef-cookbooks/

They are included in this repo as a convenience, but they are not maintained by our team. See https://github.com/facebook/IT-CPE/blob/main/CONTRIBUTING.md for more information
