### ISSUE TITLE
Sevenzip artifact

### ISSUE THREAD

**Issue by ChefAustin** [facebook/IT-CPE#267]
Need to add `def self.sevenzip_cmd` to `cpe_helpers` and re-ref it in `cpe_remote` so it is being called from `CPE::Helpers` and not `CPE::Utils`. 

https://github.com/facebook/IT-CPE/blob/9230cdb172240130bb530106fc21400284a6117c/itchef/cookbooks/cpe_remote/resources/zip.rb#L80

**Comment by dtheyer** [comment]
Thanks for reporting this, sevenzip_cmd is now available in cpe_helpers
