### ISSUE TITLE
Unable to upload cpe_utils cookbook

### ISSUE THREAD

**Issue by jmac810** [facebook/IT-CPE#28]
Missing 'maintainer_email' entry in cpe_utils/metadata.rb

Fix: When running knife upload, the upload consistently fails. Adding that metadata field fixes the error.

**Comment by mikedodge04** [comment]
Can you give me the full stack trace.  Or a pr?

**Comment by mikedodge04** [comment]
never mind. I think i fixed it. Let me know if you have any more issues, and thanks for reporting.
