### ISSUE TITLE
/Library/Preferences/SystemConfiguration/com.apple.PowerManagement.plist

### ISSUE THREAD

**Issue by cgerke** [facebook/IT-CPE#61]
In reference to the cpe_osxserver cookbook (which may be redundant now that you have cpe_macos_server). Looks like Apple moved this in Sierra.

I see two files now when using profiles;
/Library/Preferences/com.apple.PowerManagement.plist
/Library/Preferences/com.apple.PowerManagement.${UUID}.plist

**Comment by nmcspadden** [comment]
I will update the open-source cpe_osxserver_cookbook after I rewrite it.
