### ISSUE TITLE
cpe_powermanagement

### ISSUE THREAD

**Issue by cgerke** [facebook/IT-CPE#62]
I run a headless MacMini 7,2 at home and the cpe_powermanagement cookbook fails as it tries to install a portable profile.

Ohai returns

"battery": {

```
}
```

**Comment by natewalck** [comment]
Which version of chef/ohai are you on?

**Comment by cgerke** [comment]
Ohai: 8.20.0
Chef Client, version 12.14.89

**Comment by nmcspadden** [comment]
So I see. I can repro. I guess at some point, ohai changed this and now 'battery' is just an empty hash on Mac Minis and Mac Pros.

**Comment by nmcspadden** [comment]
https://github.com/facebook/IT-CPE/pull/65

**Comment by cgerke** [comment]
:+1:
