### ISSUE TITLE
Chef run crashes due to cpe_munki_install out of the box

### ISSUE THREAD

**Issue by discentem** [facebook/IT-CPE#70]
I changed only the following attributes:

`node.default['organization'] = 'bkCo'`
`node.default['cpe_launchd']['prefix'] = 'com.bkCo.chef'`
`node.default['cpe_profiles']['prefix'] = 'com.bkCo.chef'`

Running `sudo chef-client -z -j quickstart.json` results in a crash. See https://gist.github.com/discentem/4b19b516ae1318f3008f79d06adef40d for fatal output. 

Commenting `cpe_munki` out in the runlist in mac_os_x_init.rb results in a finished run (no crash).

**Comment by mikedodge04** [comment]
I see the issue. I will have a fix soon.

**Comment by discentem** [comment]
@mikedodge04 Cool. Thanks!

**Comment by mikedodge04** [comment]
fix is ready, just testing.

**Comment by discentem** [comment]
Thanks @mikedodge04 :)

**Comment by achand** [comment]
https://github.com/facebook/IT-CPE/pull/71

**Comment by mikedodge04** [comment]
Let us know if you are still having issues

**Comment by discentem** [comment]
Will test soon, sorry! Currently bogged down with school finals.

**Comment by discentem** [comment]
Clone fresh. Set the following:

node.default['organization'] = 'bkCo'
node.default['cpe_launchd']['prefix'] = 'com.bkCo.chef'
node.default['cpe_profiles']['prefix'] = 'com.bkCo.chef'

Still crashes. https://gist.github.com/discentem/02fdba7b4c108eaabbb3560392951758
