### ISSUE TITLE
node['cpe_munki']['preferences']['LocalOnlyManifest'] = 'extra_packages' has to be explicitly set

### ISSUE THREAD

**Issue by discentem** [facebook/IT-CPE#82]
I'm not sure if this is exactly the relevant line, however, in any case, the default fallback setting for  `node['cpe_munki']['preferences']['LocalOnlyManifest']` doesn't get added to the Munki profile.

https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_munki/resources/cpe_munki_local.rb#L30

This preference doesn't get applied unless it is explicitly set. Currently I'm setting this in `cpe_init::company_init.rb`.

**Comment by natewalck** [comment]
Looked at this, it appears that the configure resource just stuffs whatever is in the attributes into the profile. That is perfectly fine, but I'll add a check for LocalOnlyManifest and make sure it is set either way, unless there are objections. @mikedodge04 @nmcspadden

**Comment by mikedodge04** [comment]
Its and order issue. 
https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_munki/recipes/default.rb#L18

the local need to come before config, and then it will work.
