### ISSUE TITLE
autodmg_cache_build lacks verbosity/unexpected behavior when specifying repo

### ISSUE THREAD

**Issue by arubdesu** [facebook/IT-CPE#9]
I had an issue where the repo pointed to was being used to pull pkgs, but not manifests (I nettop'd it and was only seeing the http repo, but am using puppet+client certs on the build box). More verbosity would have been nice to help me detect the confusion earlier.

**Comment by nmcspadden** [comment]
Try the latest commit (https://github.com/facebook/IT-CPE/commit/f522a2dc0807c652d904af0ad5291a51254c1820) on admg_dev and let me know if this helps address it.

Good news: I fixed the problem where it wasn't finding things from a separate repo
Bad news: it now downloads it into the built-in Munki cache as well as the AutoDMG cache folder

**Comment by nmcspadden** [comment]
I'm closing this issue as I currently do not intend to officially support this in the master branch.
