### ISSUE TITLE
Example quickstart not currently noop due to cpe_chrome and cpe_screensaver defaults

### ISSUE THREAD

**Issue by arubdesu** [facebook/IT-CPE#93]
In [the readme](https://github.com/facebook/IT-CPE/blob/master/chef/README.md) I think it should be clearly stated what changes are expected to happen. Applying the default quickstart.json results in two profiles appearing, for managing screensaver and chrome, which I think should be no-op by default. Un-intuitively, no munki changes occur, so it's extra confusing.

Muting this behavior for chrome requires adding this to `IT-CPE/chef/cookbooks/cpe_init/recipes/company_init.rb`:

``
node.default['cpe_chrome']['profile'] = {}
``
I don't know how to nerf cpe_screensaver...

While we're discussing the readme, I'd also spell out the chef-zero --local-mode and --override-runlist flags for the non-savvy.

**Comment by erikng** [comment]
I do agree that both cpe_screensaver and cpe_chrome should not setup defaults. I've worked around both of these but it may not be obvious to others.

That said, when these were open sourced, these finer details may have been missed.

Thanks,
Erik Gomez
________________________________

**Comment by mikedodge04** [comment]
For the screen saver piece of it 
https://github.com/facebook/IT-CPE/pull/133

**Comment by mikedodge04** [comment]
For the chrome piece of it
https://github.com/facebook/IT-CPE/pull/134

**Comment by mikedodge04** [comment]
Fixed with attached PRs
